---
version: 2

project_name: ds2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: default
    <<: &build_defaults
      env:
        - CGO_ENABLED=0
      binary: ds2
      ldflags:
        - -s -w
        - -X DockSTARTer2/internal/version.Version={{.Version}}
        - -X DockSTARTer2/internal/version.Commit={{.Commit}}
        - -X DockSTARTer2/internal/version.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
  - id: armv6
    <<: *build_defaults
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "6"

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip


changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: GhostWriters
    name: DockSTARTer2
  prerelease: auto
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true
