---
version: 2

project_name: ds2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    binary: ds2

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - maintainer: nemchik <nemchik@gmail.com>
    description: DockSTARTer - easiest way to get started with Docker
    homepage: https://dockstarter.com
    license: MIT
    formats:
      - deb
      - rpm
    overrides:
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
      rpm:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: GhostWriters
    name: DockSTARTer2
  prerelease: auto
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true
