---
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Default state for all rules
default: true

# MD024/no-duplicate-heading : Multiple headings with the same content : https://github.com/DavidAnson/markdownlint/blob/main/doc/md024.md
MD024:
  # Only check top-level headings
  siblings_only: true

# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md
MD033: false

# MD034/no-bare-urls : Bare URL used : https://github.com/DavidAnson/markdownlint/blob/main/doc/md034.md
MD034: false

# MD059/link-text-should-be-descriptive : Link text should be descriptive : https://github.com/DavidAnson/markdownlint/blob/main/doc/md059.md
MD059: false